### ISSUE TITLE
Building Issues

### ISSUE THREAD

**Issue by JasonBSteele** [slodge/BallControl#1]
Hi Stuart, trying to build using VS 2012
1. Quite a few (but not all) of the references to Cirrious.MvvmCross.dll seem to be broken so had to re-add
2. I get the following error when build the Core
   "The type 'System.ComponentModel.INotifyPropertyChanged' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.    "

**Comment by slodge** [comment]
I think it's because I checked in the portable libs from MonoDevelop on Mac - still some tooling problems to sort through there....

Hopefully the checkin I just did will help there.

**Comment by JasonBSteele** [comment]
Hi Stuart, 
I've recently installed Win8 and VS2012. So I've just re-installed VS2010, SP1, PCL v2, Nuget, MonoDroid and tried to build in VS2010.

I'm still getting missing "Cirrious.MvvmCross.Console" references for the following:
Cirrious.MvvmCross.Plugins.Sphero.Droid
Cirrious.MvvmCross.Plugins.XamPhotos.Droid
Cirrious.MvvmCross.Plugins.Speech.Droid

and a missing "Cirrious.MvvmCross.Console" for Cirrious.Sphero.WorkBench.Core

Also Core is still complaining about  'System.ComponentModel.INotifyPropertyChanged'

**Comment by slodge** [comment]
I think the problem was 'lack of sleep'

I've merged the branch 'WinRTHacking' back with 'master' - sorry I was pushing to a temporary branch but didn't realised.

Don't worry about getting WinRT working.... but see if you can get Droid building...

**Comment by slodge** [comment]
If in VS2012 you find you need to build Droid projects twice then please log this with Xamarin via forums and/or Bugzilla... they do care, but sometimes they need a few nudges :)

**Comment by slodge** [comment]
Really feeling very very guilty you installed all that stuff....

**Comment by JasonBSteele** [comment]
Hey no worries, I had to get that stuff installed again at some point - and I couldn't sleep so it was reclaimed time anyway :)

So the Core is building and the refs look good, but I have another issue with the Droid projects. I've tried reloading them but I get an error box saying "Unable to add a reference to project blah.Accelerometer. The current project's target framework is not compatible with the target frameworks of PL project blah.Accelerometer'

If I look at its properties I see that Mono for Android is not ticked as a target framework. If I click it the OK button is disabled and a message saying that there is no common functionality is shown. (This is all in VS 2010).

**Comment by slodge** [comment]
Have you got XML files installed for profile104?

**Comment by JasonBSteele** [comment]
In C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETPortable\v4.0\Profile\Profile104\SupportedFrameworks I have a file called "MonoAndroid,Version=v1.6+.xml" with

<?xml version="1.0" encoding="utf-8"?>
<Framework DisplayName="Mono for Android"
  Identifier="MonoAndroid"
  Profile="*"
  MinimumVersion="1.6"
  MaximumVersion="*" />

inside it. Do I need to do anything else?

**Comment by JasonBSteele** [comment]
It gets wierder... The Sphero.Droid project is happily referencing the Sphero project and when I take a look at its target's "Mono for Android" is ticked. Speech and XamPhotos are also okay, all the other Plugins are not.

**Comment by JasonBSteele** [comment]
Tried opening it in VS2012 and that problem seemed to go away but then ended up with a lot of new problems:
Cirrious.MvvmCross not referenced in Cirrious.MvvmCross.Plugins.Settings.Droid and Cirrious.MvvmCross.Plugins.Settings.WindowsPhone, and several other broken references.

**Comment by slodge** [comment]
Slow down... Diff against source control if needed.

this is fiddly but tools getting closer.

check - do all your PCL csproj files still say 104 in them.

then go to ui Droid project, choose rebuild all. If it fails first time, then try build again - or switch to v2010

will be in jabbr soon if that helps

**Comment by slodge** [comment]
Deep breaths 

toy working soon I promise

**Comment by slodge** [comment]
On a train but in http://jabbr.net/#/rooms/mvvmcross if that helps :)

**Comment by slodge** [comment]
WooHoo - Jason has it built :)
